### ISSUE TITLE
update product text font to something more readable

### ISSUE THREAD

**Issue by matthird** [toastcreative/fairview#16]
The body text – Is there a similar font that is more reader friendly? I think the current font would be great for pull-quotes etc, but not for big lots of text. please update throughout site

get Reuben and Rachel to approve before rollout

**Comment by toastadmin** [comment]
Yo Rach, what do you think of Roboto condensed?

![screen shot 2015-04-17 at 9 44 54 am](https://cloud.githubusercontent.com/assets/8654279/7193601/71bb423e-e4e6-11e4-941c-0d2b7168f69a.png)

**Comment by RachelBatty** [comment]
looks good to me - should check with Reuben too, can you send us the test link to approve? 
Thanks
